@startuml BaselineDocuOverview
/'rectangle "Market Requirement Document (MRD)" as MRD'/
/'rectangle "Continuous-Driven Development Document (CDDD)" as CDDD '/
/'rectangle "GUI Product Requirements Document (GPRD)" as GPRD'/
rectangle "Software Development Plan (SDP)" as SDP
'component "generated"{
    rectangle "Concept Design Document (CDD)" as CDD
    rectangle "Coding Conventions Document (CCD)" as CCD
    rectangle "Software Requirement Document (SRD)" as SRD
    rectangle "Software Component List (SCL)" as SCL
    rectangle "Software Development Environment (SDE)" as SDE
    rectangle "Software Release Notes (SRN)" as SRN
    rectangle "Test Analysis Report (TAR)" as TAR
    rectangle "Test Analysis Specification (TAS)" as TAS
    rectangle "Revision Level History (RLH)" as RLH
    rectangle "SOUP Component List (SOL)" as SOL
'}

'MRD --> CDDD
'MRD --> SDP
SDP -[#A9DCDF]-> CDD
SDP -[#A9DCDF]-> SRD
'CDDD --> CDD
'SDP <--> CDDD
'CDDD --> SRD
CDD --- CCD
CDD --> SDE
SRD --> TAS
TAR --> SRN
TAS --> TAR
SOL --> SCL
SCL --> SRN
SRN --> RLH

@enduml
